name = "ImagineInterface"
uuid = "a9d8408c-0fb1-11e9-0067-cb067474114e"
version = "0.1.7"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ImagineFormat = "4bab44a2-5ff2-5a6b-8e10-825fb9ac126a"
ImagineHardware = "75ec5d3c-0ed3-11e9-24c7-e530058603ef"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnitAliases = "96ae54c0-0dff-11e9-11b2-27e67f6cc5ea"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AxisArrays = "0.4"
DSP = "0.6, 0.7, 0.8"
DataStructures = "0.17, 0.18"
ImagineFormat = "1"
ImagineHardware = "0.0.1"
IntervalSets = "0.4, 0.5, 0.6, 0.7"
JSON = "0.21"
MappedArrays = "0.2, 0.3, 0.4"
Statistics = "1"
UnitAliases = "0.0.1"
Unitful = "1"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
